### PR TITLE
Merge recompiled hex file for servo emu + programmer doc

### PR DESCRIPTION
**Pull request by furrtek**

### CODE REVIEW

**Comment by itslemcy** [comment]
awesome!

**Review by itslemcy — APPROVED** [review]

**Review by itslemcy — APPROVED** [review]

**Review by itslemcy — APPROVED** [review]

**Comment by Icelvlan88** [comment]
I'm seeing some horizontal lines when I used the servo code, possible there is a bug?

**Comment by itslemcy** [comment]
> I'm seeing some horizontal lines when I used the servo code, possible there is a bug?

@Icelvlan88 have you flashed the attiny with the correct parameters of the screenshots i've uploaded?

**Comment by Icelvlan88** [comment]
Issue was resolved

**Pull request merged**
